# Site
repository: kamesh-se/kamesh-se.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kamesh
title: Lead engineer  
email: kamesh.chandran@gmail.com
website: kamesh-se.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: kamesh-se
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kameshchandran
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "G-V1Y5X4WH7L"
gtag: "G-V1Y5X4WH7L"
google_analytics: "G-V1Y5X4WH7L"

# About Section
# about_title: About Me
about_profile_image: images/1-sticker.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Kamesh and I have 15+ years of versatile experience in Lead Engineering, Fraud detection, Data Center, Order Management, reseller, Banking  (Merchant and Customer banking portal), Design & Development of the portal, REST-Based servicing application (Middleware/Micro Service application). Presently associated with Equinix, Singapore as Senior Staff Engineer (Lead engineer).
  
  
  **Core Competencies**:
  - Data Architect 
  - API Evangelist
  - Solution Architect (AWS Cloud)
  - Problem Solving
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left 
        title: Grab
        link: grab.com
        sub_title: Lead Data Engineer
        caption: September 2021 - Present
        icon: fab fa-github
        quote: >
          Grab Holdings Limited provides superapps that allows access to mobility, delivery, financial services, and enterprise offerings through its mobile application in Cambodia, Indonesia, Malaysia, Myanmar, the Philippines, Singapore, Thailand, and Vietnam. The company is headquartered in Singapore
        description: |
          Grab - the leading super app in Southeast Asia - combines transport, food delivery, logistics, financial services, and much more in a single platform. The TIS (Trust, Identity & Safety) department acts as guardians of all users on Grab. It closely monitors every event such as account login, booking and transactions on the platform for over 8 major business lines across Grab, making data driven decisions in milliseconds. The current organization has given me the most challenging <mark>anti-fraud detection</mark> problem to solve with <mark>11+ months</mark> association.


          **Modules Lead and contributed**:
          - Work on problems that run the gamut from data science to deploying and monitoring models in production.
          - Build and deploy scalable machine learning models to enable our fraud, risk and safety systems.
          - Analyze data and define metrics for feature evaluation and model performance.
          - Design and implement robust data pipelines.
          - Identify and build new approaches and methods for machine learning as we grow.
          - Framework and technical:  Java 11, Scala, Flink, Elasticsearch, Kafka Streaming, Terragrunt, AWS EC2, S3 and DynamoDB.
      - layout: left
        title: Equinix
        link: customerportal.equinix.com
        sub_title: Senior Staff Engineer (Lead Engineer)
        caption: December 2015 - September 2021
        icon: fab fa-github
        quote: >
          Equinix's single global platform helped digital leaders stay out front for more than 20 years. Interconnect your digital infrastructure to scale with agility, leveraging leading enterprises and service providers in ecosystems that multiply value for all. At Equinix, we see every day as a fresh opportunity to help you fast track your digital advantage.
        description: | # this will include new lines to allow paragraphs
          Equinix's Colocations platform provides interconnections between digital enterprises. The customer can avail the colocations services offered and provides all the aftermarket facilities like billing in a single unified platform. Customers can utilize multiple channels, web, mobile, and Partner API for direct Integration. The organization has given me the most challenging data center industrial problem to solve with <mark>6+ years</mark> association.


          **Modules Lead and contributed**:
          - Enterprise Search Engine - Search is a permission drive search engine; this allows the user to multilingual search queries to find relevant information. Relevancy and racking are designed based on business domain fields to provide a seamless user experience. 
          - Unified Notifications service - Unified notification message services with services like firebase, MS teams, Azure queue, SMS, and email. 
          - Interconnection LOA management - The LOA process helps an approval process that allows establishing connection between two customers. 
          - Machine learnings projects
            - Smart Discovery - Discovering the user actions based on users' attachment or description. Based on attachment content or request descriptions, the ML model will recommend order types and pre-populate the necessary details. 
            - Order Recommendation - This ML models recommend that the user place the connected orders based on frequent action. ML model allows to reduce the number of clicks and predicts the dependent orders. 
      - layout: left
        title: FIS (Fidelity information's Solution)
        link: fisglobal.com
        sub_title: Technical Lead Engineer
        caption: July 2014 - December 2015
        quote: >
          FIS stays ahead of how the world is evolving to power businesses, across merchants, banking and capital markets, to outpace today’s fast-changing competitive landscape and help our clients run, grow and achieve more for their business. 
        description: | # this will include new lines to allow paragraphs
          The organization needs banking solutions online to facilitate the buyer and seller to check the balance and make payments. I was the lead engineer to provide generic solutions for merchants and customers to view and manage any transaction life cycle. Portal will help the FIS Customer get them out of the box solutions with a white labeling option. The organization has given me multiple opportunities to mature my industrial banking experience in a short period of <mark>1.6 years</mark>.           
          
          **Modules Lead and contributed**:
          - Merchant Portal - Facilitates mPOS device association with seller. This portal provides seller to manage successful transactions and refunds. The frameworks used in this project are <mark>Angular JS</mark> as single page applications backed by middleware technology <mark>Spring 4.x, Java 8 and Nginx</mark>
          - Prepaid Customer Portal (Mobile wallet)- Facilitates mPOS device association with seller. This portal provides seller to manage successful transactions and refunds. The frameworks used in this project are <mark>Angular JS</mark> as single page applications backed by middleware technology <mark>Spring 4.x, Java 8 and Nginx</mark>
          - OTP platform Service - One time password solutions used as 2 factor authentications for any payment authorizations or authorizing user for verifications. The frameworks use in this project are Apache Camel, Scala, SMS Gateway services.
          - POC:
            - Aadhaar based KYC approval for customer - Creating back account based on aadhaar mobile number and finger print solutions to create a back account. The frameworks use in this project are Angular JS, Apache Cordova, finger print scanner, android. 
      - layout: left
        title: HTSL (Honeywell Technology Solutions Lab)
        link: aerospace.honeywell.com
        sub_title: Technical Lead Engineer
        caption: July 2006 - April 2014
        quote: >
         Honeywell Technology Solutions Lab Private Limited is a computer software company
        description: | # this will include new lines to allow paragraphs
          Portal has the ability to airplane product orders and manages the warranty for Honeywell aerospace-related offerings. Portal facilitates engineers to download engine technical documentation based. Customers will have the option to make payment for the rented airplane engines or services offerings. During <mark>7.6 years</mark> of the journey, organizations have given me multiple opportunities to mature aerospace industrial experience. I played various roles from time to time for 16 months as an on-site coordinator, five years as a technical lead with a team size of 10 members, two years as an engineer, and six months as an intern trainee. During my organizations' journey, I was an active member in evaluating technology and innovative solutions. 
         
          
          **Modules Lead and contributed**:
          - Aerospace Portal - A leading web portal for Honeywell Aerospace customer and Customer support representatives to place orders, collate information on the order, download the technical document, and search for field service engineer and support locator. The frameworks used in this project are <mark>Websphere Portal 7, Sprint Portlets and Generic portlets</mark>. 
          - SHARED Portal Migration - Enable Honeywell’s airline customers to access value-added aftermarket service for their MRO requirements through migration of SHARED system functionality to the MyAerospace portal. Solutions is based on Spring 3.x, MyBatis, Ajax and Websphere portal server.
          - Plymouth Migration - Reselling portal enabling customers & employees to search & browse through the catalog, add to cart and process with placing an order. The frameworks used in this project are SAP ECC eSelling, XCM, NWDS.
          - ATR Catalog - Enable internal Honeywell’s sales rep to access ATR catalog form any mobile device. This allows configuring and downloading the catalog online and persists them on the devices. Especially when they are in the Aero show conference 
          - Other Projects
            - HSCE - Honeywell Health and Safety system Portal
            - Teardown Management system - Barcode generation, for comparing LCD productions for Honeywell Patterns
            - HonBoard - Online whiteboard solutions like "Miro"
            - Catalogic - IPad Applications for Aerospace Catalog for sales and marketing.
            - Integrated Supply chain - <mark>SAP Enterprise Portal</mark> Solution based for Supply chain management. 
            - Single Singe On Integration - using saml defining authorizations and authentications between multiple systems

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The University of Texas, Executions Educations
        caption: 2019 - 2020
        sub_title: Post Graduate certificate Program - Artificial intelligence and Machine learning
        link: |
          eportfolio.greatlearning.in/kamesh
        quote: >
          The University of Texas at Austin, shortened to UT Austin, UT, or Texas, is a public research university in Austin, Texas and the flagship institution of the University of Texas System.
        description: | # this will include new lines to allow paragraphs
          I learn to create and manage machine learning models during the modern way of online education—the basics skill like cleansing the data for model prediction, PCA, and Feature engineering. I learned to organize the data and understand the business use case to predict the models.
      - layout: left
        title: JJ College of engineering (Affiliated to Anna University)
        caption: 2003 - 2006
        sub_title: BE Computer Science
        quote: JJ Colleger of Engineering affiliated to Anna University
        description: | # this will include new lines to allow paragraphs
          During my time at College I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *College Developer Community* taking on roles such as arranging hacking sessions for juniors *Hackathon Organizer* and *Cultural Event Vice-President*.
      - layout: left
        title: Department of Technical Educations
        caption: 2000 - 2003
        sub_title: Diploma in Computer Technology 
        quote: KAR Polytechnic college, Ambur, Tamilnadu, India
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI, ML and software engineering some of my other interests and hobbies are:
      - Running
      - Writing blogs [link](https://kamesh-c.medium.com/) 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-ta
